<?php

namespace App\Exports;

use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithStyles;
use PhpOffice\PhpSpreadsheet\Worksheet\Worksheet;

class OlympiadAccessCodeExport implements FromCollection, WithHeadings, WithStyles
{
    protected $accessCodes;

    public function __construct($accessCodes)
    {
        $this->accessCodes = $accessCodes;
    }

    // Data to export
    public function collection()
    {
        return $this->accessCodes->map(function ($accessCode, $index) {


            return [
                'S.No' => $index + 1,
                'Book Series Name' => $accessCode->series_name ?? 'N/A',
                'Class' => $accessCode->class_name ?? 'N/A',
                'Subject' => $accessCode->subject_name ?? 'N/A',
                'Access Code' => $accessCode->access_code,
                'Genration Date' => $accessCode->generation_date ?? 'N/A',
                'Expired Date' => $accessCode->expiration_date ?? 'N/A',
                'Generated By (User Name)' => $accessCode->code_generator_name ?? 'N/A',
                'Status' => config('constants.STATUS_LIST')[$accessCode->is_active] ?? 'N/A',
                'Used By' => $accessCode->usedBy->name ?? 'N/A',
            ];
        });
    }

    // Headings for Excel/CSV
    public function headings(): array
    {
        return [
            'S.No',
            'Book Series Name',
            'Class',
            'Subject',
            'Access Code',
            'Genration Date',
            'Expired Date',
            'Generated By (User Name)',
            'Status',
            'Used By',
        ];
    }

    // Apply styles to the header
    public function styles(Worksheet $sheet)
    {
        return [
            1 => [ // Row 1 (header row)
                'font' => [
                    'bold' => true,
                ],
                'fill' => [
                    'fillType' => \PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID,
                    'startColor' => [
                        'rgb' => 'FFFF00', // Yellow background color
                    ],
                ],
            ],
        ];
    }
}
